server:
  port: 8090
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8080
          client-id: client1
          client-secret: secret
      permit-pattern:
        - "/public/**"
logging:
  config: classpath:log4j2.xml
  log-request: true
  log-response: true

cors:
  allow-credentials: true
  allowed-origins:
    - "http://localhost:4200"
    - "http://test-cookie.vn:4200"
