server:
  port: 8090
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: amilo-service
          jwk-set-uri: http://localhost:8080/oauth/token/.well-known/jwks.json