server:
  port: 8090
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: common-issuer
          jwk-set-uri: http://localhost:8080/oauth/token/.well-known/jwks.json

logging:
  config: classpath:log4j2.xml
