server:
  port: 8090
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8080/oauth/check_token
          client-id: client1
          client-secret: secret

logging:
  config: classpath:log4j2.xml
  log-request: true
  log-response: true
